[lints]
workspace = true

[package]
name = "may-i-sexpr"
version = "0.1.0"
edition = "2024"

[dependencies]
may-i-core = { path = "../core" }
may-i-pp = { path = "../pp" }
proptest = { version = "1", optional = true }

[features]
test-generators = ["proptest"]

[dev-dependencies]
proptest = "1"

# No doctests in this workspace; skip the harness build.
[lib]
doctest = false
