[lints]
workspace = true

[package]
name = "may-i-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
may-i-shell-parser = { path = "../shell-parser" }
may-i-core = { path = "../core" }
arbitrary = { version = "1", optional = true }
proptest = { version = "1", optional = true }

[features]
arbitrary = ["dep:arbitrary", "may-i-core/arbitrary"]
test-generators = ["proptest", "may-i-core/test-generators"]

[dev-dependencies]
may-i-config = { path = "../config" }
may-i-core = { path = "../core", features = ["test-generators"] }
proptest = "1"
regex = "1"
